### PR TITLE
Hotfix/add save bug

### LINKED ISSUE #447: Bug: Routing: there is a too-open search for `add` to change to `save`
If a content type contains the word `add`, the routing attempts to replace it with the word `save`

## Steps for Reproducing

- Create a content type with the word `add` in the name, like `add-on`
- Attempt to save an `add-on` in the CMS
- Note that it results in a 404 page because it can't find the content type `save-on`

## Screenshots
image

## Affected Browsers

- [ ] All

## Runtime Version

5.11

## Code Version

2.10.0
---

### PR DESCRIPTION
**Pull request by scottnath**
Error was with how the `action` was created for the form on the `add` page. Confirmed repair with integration test.

---
Resolves #447 

`DCO 1.1 Signed-off-by: Scott Nath <github@scottnath.com>`

### CODE REVIEW

File: lib/routes/content.js [hunk 1]
```diff
@@ -215,7 +215,7 @@ const routes = application => {
             return types.form(merged, errors, config).then(form => {
               res.render('content/add', {
                 form,
-                action: `/${config.content.base}/${req.params.type}/${config.content.actions.save}`,
+                action: `/${config.content.base}/${req.params.type.toLowerCase()}/${config.content.actions.save}`,
```
Comment (Snugug) [inline lib/routes/content.js]: This all looks good. Just requesting that a few tests are written so we can catch this before it crops up again?

Comment (scottnath) [inline lib/routes/content.js]: @Snugug cannot test this because the routes are not yet pulled out of the `content` section. [this comment on the refactor story](https://github.com/punchcard-cms/punchcard/issues/218#issuecomment-249609951) captures the need to add a test that the `action` attribute is what we expect it to be.

ie...cannot add a test now, unless we make it an E2E test in `server.js`. Which is dumb. I hate that file. I haet
ihaetusohard
 that file so hard.
