### PR TITLE
errors not caught with custom err handler

### LINKED ISSUE #312: Error route refactor
Errors are not ending up in our custom error handler. 

```gherkin
Feature: Error handling through routes
  As a core developer
  I want to have errors use our custom route error handler
  So that I can control how our error pages work

  Scenario: Convert error routes
    Given that some code can be broken out of routes
     When I need to fix error routing
     Then I should create new code and tests to cover the repaired route code.

  Scenario: Cascade error route changes
    Given that errors are going to be triggered in a different way
    When I fix the error route for generic errors
    Then I need to fix any error triggers in existing routes to use the updated routes
```

---

**Unit Testing**
- [x] Convert
- [x] Cascade

### PR DESCRIPTION
**Pull request by scottnath**
This covers a bug which makes our app ignore the error route we created. Instead it uses Express' built in error route page currently.

Also upgrading error routes to be more test-able! What fun!

---
Resolves #312

`DCO 1.1 Signed-off-by: Scott Nath <github@scottnath.com>`

### CODE REVIEW

File: lib/errors/routes.js [hunk 1]
```diff
@@ -0,0 +1,76 @@
...
+      error.message = err;
+    }
+
+    error.error = {};
+
+    // If in development, will print stacktrace
+    if (app.get('env') === 'development') {
+      error.error = err;
+    }
+
```
Comment (Snugug) [inline lib/errors/routes.js]: If `status===404`, use our 404 render

File: lib/routes/errors.js [hunk 2]
```diff
@@ -21,16 +21,7 @@ module.exports = application => {
...
-      const safe = _.get(req.session, '404.safe');
-
-      _.unset(req.session, '404');
-
-      res.status(404);
-      res.render('404', {
-        message,
-        safe,
-      });
+      return routes.notFound(req, res);
```
Comment (Snugug) [inline lib/routes/errors.js]: Can we call this `routes.missing` instead of `notFound` just so we can avoid `camelCase`?

File: lib/routes/users.js [hunk 3]
```diff
@@ -111,7 +111,8 @@ const routes = application => {
         if (rows.length < 1) {
           res.status(404);
```
Comment (Snugug) [inline lib/routes/users.js]: Instead of setting status here, can we build an error object and have our error handler deal with this? This will help ensure we don't accidentally set our status multiple times.

File: tests/errors.js [hunk 4]
```diff
@@ -0,0 +1,139 @@
+import test from 'ava';
+import events from 'events';
+import httpMocks from 'node-mocks-http';
```
Comment (Snugug) [inline tests/errors.js]: why not `mocks`?

File: tests/errors.js [hunk 5]
```diff
@@ -0,0 +1,139 @@
...
+import _ from 'lodash';
+
+import routes from '../lib/errors/routes';
+
+const EventEmitter = events.EventEmitter;
+
+// used in a promise below
+let nextCalled = false; // eslint-disable-line no-unused-vars
```
Comment (Snugug) [inline tests/errors.js]: why not `called`

Comment (Snugug) [inline tests/errors.js]: Why are you setting this up outside the function call? Why can't this live inside the `next` mock?

File: tests/errors.js [hunk 6]
```diff
@@ -0,0 +1,139 @@
...
+  get,
+};
+
+/**
+ * Next
+ * @param  {object} err - the error object
+ * @returns {object} nextCalled - the error object
+ */
+const next = (err) => {
+  nextCalled = err;
```
Comment (Snugug) [inline tests/errors.js]: Here, for instance (https://github.com/punchcard-cms/punchcard/pull/313/files#r76660294)

File: tests/errors.js (hunk 4 above)
Comment (Snugug) [inline tests/errors.js]: or `http`

File: tests/errors.js [hunk 7]
```diff
@@ -0,0 +1,139 @@
...
+//////////////////////////////
+// Routes - 404
+//////////////////////////////
+test.cb('404 error route', t => {
+  const request = httpMocks.createRequest({
+    method: 'GET',
+    url: '/some/madeup/icky/path',
+  });
+
+  request._setSessionVariable('404', {});
```
Comment (Snugug) [inline tests/errors.js]: Does this need to be two different lines?

File: tests/errors.js [hunk 8]
```diff
@@ -0,0 +1,139 @@
...
+
+  _.set(request.session, '404', {
+    message: 'Something bad happened',
+    safe: '/refreshing/safe/path',
+  });
+
+  const response = httpMocks.createResponse({ eventEmitter: EventEmitter });
```
Comment (Snugug) [inline tests/errors.js]: Can we keep our `const`s together if they don't have internal dependencies on each other?

File: tests/errors.js [hunk 9]
```diff
@@ -0,0 +1,139 @@
...
+  routes.notFound(request, response);
```
Comment (Snugug) [inline tests/errors.js]: Or at the ver least some space between the two and a comment setting up the actual request/response?

File: tests/server.js [hunk 10]
```diff
@@ -755,7 +755,7 @@ test.cb('Users Edit Landing Page', t => {
     });
 });
 
-test.cb('Users Delete Landing Page', t => {
+test.skip('Users Delete Landing Page', t => {
```
Comment (Snugug) [inline tests/server.js]: Why are we skipping this test in this PR?

File: views/error.html [hunk 11]
```diff
@@ -1,8 +1,11 @@
-<h1 class="base--h1">I'm error!</h1>
+<div class="not-found">
```
Comment (Snugug) [inline views/error.html]: Why did you add an `error.html` view instead of re-using the `404` view directly?

**Comment by Snugug** [comment]
@scottnath You've got comments, and where they apply to multiple places in your code, I'd like to see those updated as well

File: views/error.html (hunk 11 above)
Comment (scottnath) [inline views/error.html]: Because I wasn't sure of the reasoning of a separate 404 vs error view. Although both using the _exact same_ template now, I wanted to leave 404 on it's own so that any changes to a 404 page in the future would not affect the general error page.

Comment (Snugug) [inline views/error.html]: ok

File: lib/errors/routes.js [hunk 12]
```diff
@@ -0,0 +1,83 @@
...
+    res.status(error.status || 500);
+
+    if (error.status === '404') {
```
Comment (Snugug) [inline lib/errors/routes.js]: Is this going to come in as a string or a number? If it comes in as a number, this is going to fail, because `===`

Comment (Snugug) [inline lib/errors/routes.js]: It looks like you're setting them as numbers FWIW

Comment (Snugug) [inline lib/errors/routes.js]: You should also include tests to check to make sure the right error handler is being hit; I would have expected this to fail your tests

**Comment by scottnath** [comment]
@Snugug changes added. waiting on CI.

File: config/default-test.js [hunk 13]
```diff
@@ -15,7 +15,7 @@ if (process.env.CI === 'true') {
       database: 'travis_ci_test',
     },
     debug: false,
-    acquireConnectionTimeout: 1000,
```
Comment (Snugug) [inline config/default-test.js]: With #323 merged, this needs to be removed/branch updated
